### PR TITLE
Json connect

### PR DESCRIPTION
**Pull request by gabrielRamaker**
Connects to JSON data by URL.  Supports caching. Documentation (and example URL) in README.md

### CODE REVIEW

**Comment by gabrielRamaker** [comment]
Signed it

**Comment by diminishedprime** [comment]
As a first step can you migrate this to using dscc-gen, you should follow the guide for [existing connectors]. We want all connectors in this repo to follow the same file/folder-structure. 

[existing connectors]: https://developers.google.com/datastudio/connector/local-development#existing_connectors

**Comment by gabrielRamaker** [comment]
> As a first step can you migrate this to using dscc-gen, you should follow the guide for [existing connectors](https://developers.google.com/datastudio/connector/local-development#existing_connectors). We want all connectors in this repo to follow the same file/folder-structure.

Thanks, that improves the workflow! 

At my first attempts to migrate the script threw an exception message "dotf is not a function". Turned out I had to install yarn first. Maybe it could be added as dependency in the documentation.

**Comment by gabrielRamaker** [comment]
Thanks, and no problem. I already suspected that the licenses might conflict.

**Comment by diminishedprime** [comment]
Thanks for the contribution!

**Pull request merged**
