### PR TITLE
Support multiple Firestore collections

### PR DESCRIPTION
**Pull request by IchordeDionysos**
Implements #183

### CODE REVIEW

**Comment by diminishedprime** [comment]
This looks pretty good, could you resolve the conflicts so I can merge this in?

**Comment by IchordeDionysos** [comment]
@diminishedprime Resolved the conflicts

**Comment by diminishedprime** [comment]
Looks like you need to run `npm run prettier` then I should be able to merge this in.

**Comment by diminishedprime** [comment]
Thanks for the PR!

**Pull request merged**
