### PR TITLE
Add Toggl Connector

### PR DESCRIPTION
**Pull request by marc-clickinsight**
This is a connector for the Toggl Reports API, Summary Report

### CODE REVIEW

**Comment by diminishedprime** [comment]
Could you switch the config & schema to use `DataStudioApp`. See #83 for what this change looks like.

**Comment by diminishedprime** [comment]
@marc-clickinsight - did you miss this one when you were updating all the others?

**Comment by marc-clickinsight** [comment]
@diminishedprime I'm having issues getting the user_token authentication to work. Need to figure that part out before updating the code here.

**Comment by diminishedprime** [comment]
closing due to inactivity. Feel free to open up a new one if you're still interested in getting this merged in!

**Pull request closed without merging**
