### PR TITLE
Senuto connector

### PR DESCRIPTION
**Pull request by analityka**

### CODE REVIEW

**Comment by diminishedprime** [comment]
Hi, could you explain a bit about what data this connector will be connecting to? This connector might be better served as a partner connector. Please see [Publish A Community Connector] for an outline of why you might pick open-source vs Partner. 

[Publish A Community Connector]: https://developers.google.com/datastudio/connector/publish-connector

**Comment by analityka** [comment]
Hi Matt,

Senuto is an SEO analytics platform and know-how consultancy. It lets you
plan, monitor, and optimize marketing activities in Google.

As an SEO Software Suite Senuto provides its clients with modules essential
to SEO specialists in their everyday work. Our continuously growing keyword
base equips our clients with numerous keyword ideas for each and every
entry, in every country and language in the world. Our Monitoring Tool on
the other hand, simplifies the process of checking the results of their SEO
campaigns, be it a new content marketing, or internal linking strategy
brought into play.

But Senuto is not only a part of many SEO experts’ toolkits. It also helps
content marketers to plan their strategy according to big data, it assists
eCommerce managers at benchmarking and supports marketing experts at
understanding their situation in Google.

When it comes to the connector itself, we’ve decided that it’s easier and
faster to fulfil all the requirements to be featured as an open source
solution and that’s actually the only reason why we’ve chosen this path. If
it’s possible for us, we’d prefer to become partner. Maybe we could start
off as an open source and then, as a next step, become a Partner?

Best Regards
Senuto Team

**Comment by diminishedprime** [comment]
We can certainly merge this is an an open-source connector, but keep in mind that our support for this is limited. 

If you need to make a fix/update to the connector, you'll have to make a PR to this repo and we can only review those as we have time. If (potentially) long delays are okay with you (and your customers), we can move ahead with the review to add this to the open-source connector, but our guidance is anything  business critical should go through the partner-path, or share deployment links directly. Otherwise you might get stuck with a deployment that isn't updated for quite a while. 

Let me know if you would like to continue ahead with adding this connector to the repo.

**Comment by analityka** [comment]
yes, please enable as open source :)

**Comment by diminishedprime** [comment]
As a first step can you migrate this to using dscc-gen, you should follow the guide for [existing connectors]. We want all connectors in this repo to follow the same file/folder-structure. 

[existing connectors]: https://developers.google.com/datastudio/connector/local-development#existing_connectors

**Comment by analityka** [comment]
Done :)

**Pull request merged**
