### PR TITLE
SendGrid's Global Stats Community Connector

### PR DESCRIPTION
**Pull request by schoraria911**
This [Data Studio](https://datastudio.google.com) [Community Connector](https://developers.google.com/datastudio/connector) lets you connect to [SendGrid](https://sendgrid.com/)'s [Global Stats API](https://sendgrid.com/docs/API_Reference/Web_API_v3/Stats/global.html) and provide all of your user’s email statistics for a given date range.

### CODE REVIEW

**Comment by diminishedprime** [comment]
Hi, if you're interested in others using this connector, I recommend you go through the steps to [Publish a Community Connector](https://developers.google.com/datastudio/connector/publish-connector) in the partner gallery.

**Comment by schoraria911** [comment]
@diminishedprime - I would definitely want others to be able to use but I don't suppose I'd be any good at being able to provide professional support (as has been required with Partner Connectors) and so choose to share this as part of the [Open Source Community Connectors](https://developers.google.com/datastudio/connector/open-source).

Do you think this qualifies for that? Or am I missing something. I did also provide with a template of my own that folks could use with the connector that I've built.

**Comment by sinklair** [comment]
@schoraria911 seems I missed that you did this. Would certainly have saved me a bunch of time getting started.

I created my own version that has support for a bunch of different stats including global stats. See https://github.com/sinklair/community-connectors/tree/master/sendgrid-statistics. I have a PR above to merge to support those.

**Comment by schoraria911** [comment]
> I created my own version that has support for a bunch of different stats including global stats.

Yours' is hella more robust than what I have built in mine 🙌🏽 perhaps I'll just withdraw this request 😅

**Pull request closed without merging**
