### PR TITLE
Add link to SPARQL Connector

### PR DESCRIPTION
**Pull request by KMax**
We've built a connector for sources implementing the SPARQL protocol and would like to have it published on the Community Connectors Gallery. Thank you in advance!

### CODE REVIEW

**Comment by KMax** [comment]
I signed it!

**Comment by KMax** [comment]
I signed it!

**Comment by diminishedprime** [comment]
This looks great, thanks for the PR.

**Comment by KMax** [comment]
@diminishedprime Awesome! Will it be listed in the Data Studio gallery?

**Pull request merged**
