### PR TITLE
Added New Community Connectors

### PR DESCRIPTION
**Pull request by marc-clickinsight**
This community connector accesses the Toggl Reports API (https://github.com/toggl/toggl_api_docs/blob/master/reports.md) and retrieves a Summary report.

### CODE REVIEW

**Comment by marc-clickinsight** [comment]
Also submitting community connectors for BART, ISS, NASA APOD, NY Times, OpenWeatherMap.

**Comment by diminishedprime** [comment]
Hey Marc, thanks for the pull request! These connectors will be great. However, to make these easier to review, I need you to make a separate pull request for each connector. Why you're at it, I see that these aren't using the Data Studio Apps Script Service. Please see [the release post] for details on how to update these to use the service.

[the release post]: https://groups.google.com/forum/#!topic/data-studio-developers/onR-075lJy8

**Comment by marc-clickinsight** [comment]
Thanks. I'll try to figure out how to make a separate pull request for each. That what I intended to do, but they all ended up together.

**Comment by marc-clickinsight** [comment]
Ok, I have split these into separate pull requests. This one can be closed.

**Pull request closed without merging**
