### PR TITLE
Migrate pagespeed insights to common file structure

### PR DESCRIPTION
**Pull request by pfrisella**

### CODE REVIEW

**Comment by grantkemp** [comment]
hi @pfrisella  - I have added some features to my local version - should I use this branch( once its added to master) to make changes. 

Is there quick way to pull this into an appscript project to build on going forward?

**Comment by diminishedprime** [comment]
Hey grant, feel free to just make changes to what's in master, then we can do this merge request after. This one was done with an automated tool so it's easy to just redo.

**Comment by grantkemp** [comment]
Thanks - I am just working on migrating it to new version of page speed insights api.  Would be good to know how I can run a prettifier in Appscript.  I can't see the option for it.

**Comment by diminishedprime** [comment]
> Thanks - I am just working on migrating it to new version of page speed insights api. Would be good to know how I can run a prettifier in Appscript. I can't see the option for it.

Looks like you ended up figuring this out, but if others find this later. To run prettier, clone the repo locally, and make sure you have `npm` installed, then run
```
npm run install
npm run prettier
npm run lint -- --fix
```
This will installed needed dependencies, prettify the code, and fix and linting issues that can automatically be fixed.

**Pull request merged**
