### PR TITLE
Version 3 - again :)

### PR DESCRIPTION
**Pull request by analityka**
prettier appscript.json

### CODE REVIEW

**Comment by diminishedprime** [comment]
Looks like you still need to run `npm run fix`. You shouldn't need to make a new PR, though, you should be able to commit your changes and push.

**Comment by analityka** [comment]
I can't run "npm run fix"  -> what is the "fix"?

I run: 
npm run prettier
npm run update_production

prettier --check '**/*.js'
Checking formatting...
All matched files use Prettier code style!

**Comment by diminishedprime** [comment]
You need to navigate to the top-level directory (probably called community-connectors), it's the one a level above the senuto directory, then you should be able to run `npm run fix`

**Comment by analityka** [comment]
Thanks a lot :)

ps.I had a newer version of prettier

**Pull request merged**
