### PR TITLE
Migrate Rankwatch connector to be google-managed.

### PR DESCRIPTION
**Pull request by diminishedprime**

### CODE REVIEW

**Comment by diminishedprime** [comment]
@rwrepoadmin - Can you check that [this Rankwatch Deployment] works as expected? Note that it's a separate deployment from yours since we need to manage the deployment. 

[this Rankwatch Deployment]: https://datastudio.google.com/c/datasources/create?connectorId=AKfycbwyueO5D9W3yGIQOrFuWKonhb_OC0_O_30MzlUfWGKk8I60A3ACgrZF0hgaaZEypm-wbA

**Comment by diminishedprime** [comment]
@rwrepoadmin - Sorry, I just remembered I'll need to share the script w/ read access before it is in the gallery. Could you share an email address that you can try the deployment from?

**Comment by rwrepoadmin** [comment]
Sure that'd be: servers@rankwatch.com the same email used for this git account.

**Comment by diminishedprime** [comment]
> Sure that'd be: [servers@rankwatch.com](mailto:servers@rankwatch.com) the same email used for this git account.

I've shared it with that email address. Could you try the deployment linked above again?

**Comment by rwrepoadmin** [comment]
All looks good to me! Connected a project and tested it as well!

**Comment by rwrepoadmin** [comment]
@diminishedprime Is there anyway I can be of help? Would be glad to assist you in pushing this ahead!

**Comment by rwrepoadmin** [comment]
Please let me know if there is any issue I can resolve to get this merged. I will be glad to help.

**Comment by diminishedprime** [comment]
In light of the recent changes for OAuth verification, We now recommend that you manage your own deployment. If you would like this connector to be listed in the gallery, you'll need to go through the [partner publishing process]. If you want your code to be removed from this repo, let me know, but feel free to keep it in. 

[partner publishing process]: https://developers.google.com/datastudio/connector/pscc-requirements

**Comment by rwrepoadmin** [comment]
Even though this connector does not have oAuth 1.0 or 2.0, I am still going to believe that this is the part where I am pushed to publish this connector as partner connector. It's ok, I understand.  However, I did as you requested, but now I will have to go through the entire process of publishing and verification again!! Is there no short way out now that the code was marked OK from you all?

**Comment by diminishedprime** [comment]
Since you already had to address feedback that would likely have been provided through the partner publishing process, it's likely that publishing as a partner connector will be quicker than usual. 

The OAuth verification is required for all AppsScripts projects that make an external requests. This is for the OAuth screen the users must click through to enable the connector before they see the config.

**Comment by rwrepoadmin** [comment]
@diminishedprime Agreed! However I quote: 

> it's likely that publishing as a partner connector will be quicker than usual

I don't feel so, it's been 4 days since I got the confirmation email stating: 

> Your connector has been added to the review queue and will be reviewed in the next 2-3 weeks. Expect to hear back from us during that time frame once your connector is approved / rejected or if we require more information.

😅 This is seems slower than community-connector! I will keep a check on my mail!
**I really appreciate you spending time over my petty issue! Thanks a TON!** 😃

**Pull request closed without merging**
